# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1aR-r1vK0nwUwrhLKxSqJAu8ji0SwRGeB
"""

def memory_addressing (page_table, page_size ,logical_address):

  # 計算頁號和偏移量

  page_number,offset = divmod(logical_address , page_size)


  # 查找頁表來獲得相應的框架號

  if page_number in page_table:

    frame_number = page_table [page_number]

    # 計算物理地址

    physical_address = frame_number * page_size + offset

    print( f"The physical address is {physical_address}")

  else:

    print("Invalid page number, address translation failed.")

# 定義頁表，其中鍵是頁號，值是框架號

page_table = {0: 5, 1: 9, 2:14}

# 定義頁大小（例如： 4096 字節）

page_size = 4096

# 定義邏輯地址（例如： 7000

logical_address = input("請輸入定義邏輯地址logical_address")

# 調用函數進行地址轉換

memory_addressing(page_table , page_size , logical_address)